language: java

jdk:
  - oraclejdk8

sudo: false

install: true

addons:
  sonarcloud:
    organization: "fdlessard-github"
    token:
      secure: "HHwlWKlcRfW/zaGR2rgiGX0X6mReuO34+pqMd0xTpAOhDHWYDi7z7o0fFYhXioUBerYE2B2G0ZEGmr7pRXNVa4HTT4JnxzLf0T/1ItSxvbS5YAyKrQfVfnEDKi90lOW6Mw6UeQMlQUs+GZcTzYpdWagsyMgjUbf+eiIDeli0fGPo9t4uyTBFhpvfP+fXjgc4VRfAE1CXFp59WhnQqxDyMD5nf6ttSXIWJ2NXFvVO2JEdZR4r5biswsy7i2/l7xj7ZVJVZrmM739L5o3m5K/eHO8o5598aOwdfoqDHPJ0Gloq8IRLaOzHqecEmuftv2ZLuKOPZ7fgk9MzzWUJR4J7C1s8nYSgNq6N2UdD1kRGKHfXuy1XYXcPetTHIb1C6jA//7i76Jxr8fDEXWyTjNhFsVuBfb9jL+qJNDmt9uh1sd+xZ2OFSe4J9EXK8Xhs2xQQcTJYifpVwBV09BxTeabg8/GRNolr7am4B7lkd+8v24kHWnqTKRBtC3EHMAHwIYS+MQh6JyCWNcgKr4P3ZyOS9uKDJaWPGtp6QMV98BPDwikaHeDVIAKdPhXxcsYDeb9hGfeNtGhMZJFmGuuJSB2pXWzDBHbO28+7VFTw6M3fLO5/SQ1kGQLxdGyOaS3/vMKffHlAQeob4znTHmXwC6my6mDzYrdkxq0QFEjw0gGF9ik="

  coverity_scan:
    project:
      name: "fdlessard/SpringBootCustomerCaching"
      description: "<Your project description here>"
      notification_email: fdlessard+gh@gmail.com
      build_command_prepend: "<Your build preprocessing command here>"
      build_command:   "<Your build command here>"
      branch_pattern: coverity_scan



script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'



env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
    - secure: "f28+jwAYl9umBK5PHLDmXHpGoOWhHUTYFCqVoOUEXn5Rocu+tVHlodDfcWbPsyWWKtWezO3mkTUskoi6qmy2aN3qbT0SNLJqQTdoEe+fbNQLjyx30RMWQwEE1C+iofHpx3dvxMXyUYygFBiPvJTEHamPfKWl2YtLv8VkLNmnLHoLU3y29RsMvFDAG/kH2LT3XHEKhCPq7x4NKUk6A5WwnukS9BqgprsL72sdwyHOhfdFISTyrJ13+HCDUeelQoh+ipKdNqubpPb7yj8JhHJ55jXEe4BcuOll/AygQacyNOHwm+fO9hClxY20NCfHCCBKfau3mdlQwM7aS66Ma+ZnW3CLZCMakVkxQrxd316qYtzNB/snL33cySoIJJR1TDxRcPzWvOwY9aJMn8s2ZEjFvZudHp0E91aqOTkf1xTdVSvVv7zbWHY8ql34FyXSfvm52HGa5i1Gkzj3xWoVWzoWxUiZU6yaXhQEXQ1K+SgbeffL+YA0YyJJ/QGT7+a/NTDpAzWaP3S0uxTNZ1or1mugo+KmZNiQ+KAivAtvQsJcGj+XmG3qwPhbuVQIk236Hwcn2ivdo5LFfShlMM4rSjeyuxNkHwAuOHf4Ped4xkP8yOxm9n3vwZ6gQnKTn4hDF8hUX0CuY/oqO/l+rjqe5pQLJnK9ShmvFfiNgQDl43ytEtY="

  before_install:
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

