spring:
  cache:
  cache-names: Customer
#   type: simple
#   type: redis
   type: jcache
   jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache.xml


#    cache-names=customers
#    type=none
#redis:
#   host: localhost
#   port: 6379



